[
  { country: "Nepal", countryCode: "NP" },
  { country: "Bangladesh", countryCode: "BD" },
  { country: "India", countryCode: "IN" },
  { country: "Pakistan", countryCode: "PK" },
  { country: "Indonesia", countryCode: "ID" },
  { country: "Thailand", countryCode: "TH" },
  { country: "Algeria", countryCode: "DZ" },
  { country: "Ethiopia", countryCode: "ET" },
  { country: "Rwanda", countryCode: "RW" },
  { country: "Morocco", countryCode: "MA" },
  { country: "Congo", countryCode: "CD" },
  { country: "United Arab Emirates", countryCode: "AE" },
  { country: "Turkey", countryCode: "TR" },
  { country: "Russia", countryCode: "RU" },
  { country: "Angola", countryCode: "AO" },
  { country: "Anguilla", countryCode: "AI" },
  { country: "Antigua and Barbuda", countryCode: "AG" },
  { country: "Argentina", countryCode: "AR" },
  { country: "Armenia", countryCode: "AM" },
  { country: "Aruba", countryCode: "AW" },
  { country: "Austria", countryCode: "AT" },
  { country: "Azerbaijan", countryCode: "AZ" },
  { country: "Bahamas", countryCode: "BS" },
  { country: "Barbados", countryCode: "BB" },
  { country: "Belarus", countryCode: "BY" },
  { country: "Belgium", countryCode: "BE" },
  { country: "Belize", countryCode: "BZ" },
  { country: "Benin", countryCode: "BJ" },
  { country: "Bermuda", countryCode: "BM" },
  { country: "Bhutan", countryCode: "BT" },
  { country: "Bolivia", countryCode: "BO" },
  { country: "Bosnia and Herzegovina", countryCode: "BA" },
  { country: "Brazil", countryCode: "BR" },
  { country: "Brunei", countryCode: "BN" },
  { country: "Bulgaria", countryCode: "BG" },
  { country: "Burkina Faso", countryCode: "BF" },
  { country: "Burundi", countryCode: "BI" },
  { country: "Uganda", countryCode: "UG" },
  { country: "Ukraine", countryCode: "UA" },
  { country: "United Kingdom", countryCode: "GB" },
  { country: "Uruguay", countryCode: "UY" },
  { country: "Uzbekistan", countryCode: "UZ" },
  { country: "Cambodia", countryCode: "KH" },
  { country: "Cameroon", countryCode: "CM" },
  { country: "Canada", countryCode: "CA" },
  { country: "Central African Republic", countryCode: "CF" },
  { country: "Chad", countryCode: "TD" },
  { country: "Chile", countryCode: "CL" },
  { country: "Colombia", countryCode: "CO" },
  { country: "Comoros", countryCode: "KM" },
  { country: "Costa Rica", countryCode: "CR" },
  { country: "Côte d'Ivoire", countryCode: "CI" },
  { country: "Croatia", countryCode: "HR" },
  { country: "Cuba", countryCode: "CU" },
  { country: "Cyprus", countryCode: "CY" },
  { country: "Czech Republic", countryCode: "CZ" },
  { country: "Denmark", countryCode: "DK" },
  { country: "Djibouti", countryCode: "DJ" },
  { country: "Dominica", countryCode: "DM" },
  { country: "Dominican Republic", countryCode: "DO" },
  { country: "Ecuador", countryCode: "EC" },
  { country: "El Salvador", countryCode: "SV" },
  { country: "Equatorial Guinea", countryCode: "GQ" },
  { country: "Eritrea", countryCode: "ER" },
  { country: "Estonia", countryCode: "EE" },
  { country: "Fiji", countryCode: "FJ" },
  { country: "France", countryCode: "FR" },
  { country: "French Guiana", countryCode: "GF" },
  { country: "Gabon", countryCode: "GA" },
  { country: "Gambia", countryCode: "GM" },
  { country: "Georgia", countryCode: "GE" },
  { country: "Germany", countryCode: "DE" },
  { country: "Ghana", countryCode: "GH" },
  { country: "Greece", countryCode: "GR" },
  { country: "Grenada", countryCode: "GD" },
  { country: "Guadeloupe", countryCode: "GP" },
  { country: "Guatemala", countryCode: "GT" },
  { country: "Guinea", countryCode: "GN" },
  { country: "Guyana", countryCode: "GY" },
  { country: "Haiti", countryCode: "HT" },
  { country: "Honduras", countryCode: "HN" },
  { country: "Hungary", countryCode: "HU" },
  { country: "Iceland", countryCode: "IS" },
  { country: "Iran", countryCode: "IR" },
  { country: "Iraq", countryCode: "IQ" },
  { country: "Ireland", countryCode: "IE" },
  { country: "Israel", countryCode: "IL" },
  { country: "Italy", countryCode: "IT" },
  { country: "Jamaica", countryCode: "JM" },
  { country: "Japan", countryCode: "JP" },
  { country: "Jordan", countryCode: "JO" },
  { country: "Kenya", countryCode: "KE" },
  { country: "Kuwait", countryCode: "KW" },
  { country: "Kyrgyzstan", countryCode: "KG" },
  { country: "Latvia", countryCode: "LV" },
  { country: "Lebanon", countryCode: "LB" },
  { country: "Lesotho", countryCode: "LS" },
  { country: "Liberia", countryCode: "LR" },
  { country: "Libya", countryCode: "LY" },
  { country: "Liechtenstein", countryCode: "LI" },
  { country: "Lithuania", countryCode: "LT" },
  { country: "Luxembourg", countryCode: "LU" },
  { country: "Macedonia", countryCode: "MK" },
  { country: "Madagascar", countryCode: "MG" },
  { country: "Malawi", countryCode: "MW" },
  { country: "Malaysia", countryCode: "MY" },
  { country: "Maldives", countryCode: "MV" },
  { country: "Mali", countryCode: "ML" },
  { country: "Malta", countryCode: "MT" },
  { country: "Martinique", countryCode: "MQ" },
  { country: "Mauritania", countryCode: "MR" },
  { country: "Mauritius", countryCode: "MU" },
  { country: "Mexico", countryCode: "MX" },
  { country: "Moldova", countryCode: "MD" },
  { country: "Mongolia", countryCode: "MN" },
  { country: "Montenegro", countryCode: "ME" },
  { country: "Montserrat", countryCode: "MS" },
  { country: "Mozambique", countryCode: "MZ" },
  { country: "Myanmar", countryCode: "MM" },
  { country: "Namibia", countryCode: "NA" },
  { country: "Netherlands", countryCode: "AN" },
  { country: "New Zealand", countryCode: "NZ" },
  { country: "Nicaragua", countryCode: "NI" },
  { country: "Niger", countryCode: "NE" },
  { country: "Norway", countryCode: "NO" },
  { country: "Oman", countryCode: "OM" },
  { country: "Palestine", countryCode: "PS" },
  { country: "Panama", countryCode: "PA" },
  { country: "Papua New Guinea", countryCode: "PG" },
  { country: "Paraguay", countryCode: "PY" },
  { country: "Peru", countryCode: "PE" },
  { country: "Philippines", countryCode: "PH" },
  { country: "Poland", countryCode: "PL" },
  { country: "Portugal", countryCode: "PT" },
  { country: "Qatar", countryCode: "QA" },
  { country: "Romania", countryCode: "RO" },
  { country: "Samoa", countryCode: "AS" },
  { country: "Saudi Arabia", countryCode: "SA" },
  { country: "Senegal", countryCode: "SN" },
  { country: "Serbia", countryCode: "RS" },
  { country: "Sierra Leone", countryCode: "SL" },
  { country: "Slovakia", countryCode: "SK" },
  { country: "Somalia", countryCode: "SO" },
  { country: "South Africa", countryCode: "ZA" },
  { country: "Spain", countryCode: "ES" },
  { country: "Sudan", countryCode: "SD" },
  { country: "Swaziland", countryCode: "SZ" },
  { country: "Sweden", countryCode: "SE" },
  { country: "Switzerland", countryCode: "CH" },
  { country: "Syria", countryCode: "SY" },
  { country: "Tajikistan", countryCode: "TJ" },
  { country: "Tanzania", countryCode: "TZ" },
  { country: "Togo", countryCode: "TG" },
  { country: "Tonga", countryCode: "TO" },
  { country: "Trinidad and Tobago", countryCode: "TT" },
  { country: "Tunisia", countryCode: "TN" },
  { country: "Turkmenistan", countryCode: "TM" },
  { country: "Turks and Caicos Islands", countryCode: "TC" },
  { country: "Venezuela", countryCode: "VE" },
  { country: "Yemen", countryCode: "YE" },
  { country: "Zimbabwe", countryCode: "ZW" },
  { country: "Nigeria", countryCode: "NG" },
  { country: "Singapore", countryCode: "SG" },
];

[
  {
    country: "Srilanka",
    correction: "Sri Lanka",
    countryCode: "LK",
  },
  {
    country: "Papua New Giuinea",
    correction: "Papua New Guinea",
    countryCode: "PG",
  },
  {
    country: "Afganistan",
    correction: "Afghanistan",
    countryCode: "AF",
  },
  {
    country: "Bostwana",
    correction: "Botswana",
    countryCode: "BW",
  },
  {
    country: "Burma (Myanmar)",
    correction: "Myanmar",
    countryCode: "MM",
  },
  {
    country: "United States of America",
    correction: "United States",
    countryCode: "US",
  },
  {
    country: "Egpyt",
    correction: "Egypt",
    countryCode: "EG",
  },
  {
    country: "Kazakshtan",
    correction: "Kazakhstan",
    countryCode: "KZ",
  },
  {
    country: "Kosovo",
    correction: null,
    countryCode: null,
  },
  {
    country: "Laos",
    correction: "Lao People's Democratic Republic",
    countryCode: "LA",
  },
  {
    country: "Macau",
    correction: "Macao",
    countryCode: "MO",
  },
  {
    country: "Reunion",
    correction: "Réunion",
    countryCode: "RE",
  },
  {
    country: "South Korea",
    correction: "Korea, Republic of",
    countryCode: "KR",
  },
  {
    country: "Vietman",
    correction: "Vietnam",
    countryCode: "VN",
  },
  {
    country: "Yugoslavia",
    correction: null,
    countryCode: null,
  },
  {
    country: "DR.Congo",
    correction: "Congo, The Democratic Republic Of The",
    countryCode: "CD",
  },
  {
    country: "People's Republic of China",
    correction: "China",
    countryCode: "CN",
  },
];
